[package]
name = "usGcode"
version = "1.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
g-code = "0.5.1"
roxmltree = "0.19.0"
svg2gcode = "0.3.3"
svgtypes = "0.13"
